# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sumo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sumo.proto',
  package='sumoprotocol',
  syntax='proto3',
  serialized_options=_b('\n\024io.grpc.sumoprotocolB\014SumoProtocolP\001\242\002\003SUP'),
  serialized_pb=_b('\n\nsumo.proto\x12\x0csumoprotocol\"+\n\x0cMotorCommand\x12\x0c\n\x04left\x18\x01 \x01(\x02\x12\r\n\x05right\x18\x02 \x01(\x02\"l\n\x0f\x44istanceSensors\x12\x12\n\nfront_left\x18\x01 \x01(\x05\x12\x13\n\x0b\x66ront_front\x18\x02 \x01(\x05\x12\x13\n\x0b\x66ront_right\x18\x03 \x01(\x05\x12\x0c\n\x04left\x18\x04 \x01(\x05\x12\r\n\x05right\x18\x05 \x01(\x05\":\n\rGroundSensors\x12\x0c\n\x04left\x18\x01 \x01(\x08\x12\r\n\x05right\x18\x02 \x01(\x08\x12\x0c\n\x04\x62\x61\x63k\x18\x03 \x01(\x08\"g\n\x07Sensors\x12/\n\x08\x64istance\x18\x01 \x01(\x0b\x32\x1d.sumoprotocol.DistanceSensors\x12+\n\x06ground\x18\x02 \x01(\x0b\x32\x1b.sumoprotocol.GroundSensors2Q\n\x0cSumoProtocol\x12\x41\n\x06SumoIO\x12\x1a.sumoprotocol.MotorCommand\x1a\x15.sumoprotocol.Sensors\"\x00(\x01\x30\x01\x42,\n\x14io.grpc.sumoprotocolB\x0cSumoProtocolP\x01\xa2\x02\x03SUPb\x06proto3')
)




_MOTORCOMMAND = _descriptor.Descriptor(
  name='MotorCommand',
  full_name='sumoprotocol.MotorCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='sumoprotocol.MotorCommand.left', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='sumoprotocol.MotorCommand.right', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=71,
)


_DISTANCESENSORS = _descriptor.Descriptor(
  name='DistanceSensors',
  full_name='sumoprotocol.DistanceSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='front_left', full_name='sumoprotocol.DistanceSensors.front_left', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_front', full_name='sumoprotocol.DistanceSensors.front_front', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_right', full_name='sumoprotocol.DistanceSensors.front_right', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left', full_name='sumoprotocol.DistanceSensors.left', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='sumoprotocol.DistanceSensors.right', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=181,
)


_GROUNDSENSORS = _descriptor.Descriptor(
  name='GroundSensors',
  full_name='sumoprotocol.GroundSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='sumoprotocol.GroundSensors.left', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='sumoprotocol.GroundSensors.right', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back', full_name='sumoprotocol.GroundSensors.back', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=241,
)


_SENSORS = _descriptor.Descriptor(
  name='Sensors',
  full_name='sumoprotocol.Sensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='sumoprotocol.Sensors.distance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ground', full_name='sumoprotocol.Sensors.ground', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=346,
)

_SENSORS.fields_by_name['distance'].message_type = _DISTANCESENSORS
_SENSORS.fields_by_name['ground'].message_type = _GROUNDSENSORS
DESCRIPTOR.message_types_by_name['MotorCommand'] = _MOTORCOMMAND
DESCRIPTOR.message_types_by_name['DistanceSensors'] = _DISTANCESENSORS
DESCRIPTOR.message_types_by_name['GroundSensors'] = _GROUNDSENSORS
DESCRIPTOR.message_types_by_name['Sensors'] = _SENSORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorCommand = _reflection.GeneratedProtocolMessageType('MotorCommand', (_message.Message,), dict(
  DESCRIPTOR = _MOTORCOMMAND,
  __module__ = 'sumo_pb2'
  # @@protoc_insertion_point(class_scope:sumoprotocol.MotorCommand)
  ))
_sym_db.RegisterMessage(MotorCommand)

DistanceSensors = _reflection.GeneratedProtocolMessageType('DistanceSensors', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCESENSORS,
  __module__ = 'sumo_pb2'
  # @@protoc_insertion_point(class_scope:sumoprotocol.DistanceSensors)
  ))
_sym_db.RegisterMessage(DistanceSensors)

GroundSensors = _reflection.GeneratedProtocolMessageType('GroundSensors', (_message.Message,), dict(
  DESCRIPTOR = _GROUNDSENSORS,
  __module__ = 'sumo_pb2'
  # @@protoc_insertion_point(class_scope:sumoprotocol.GroundSensors)
  ))
_sym_db.RegisterMessage(GroundSensors)

Sensors = _reflection.GeneratedProtocolMessageType('Sensors', (_message.Message,), dict(
  DESCRIPTOR = _SENSORS,
  __module__ = 'sumo_pb2'
  # @@protoc_insertion_point(class_scope:sumoprotocol.Sensors)
  ))
_sym_db.RegisterMessage(Sensors)


DESCRIPTOR._options = None

_SUMOPROTOCOL = _descriptor.ServiceDescriptor(
  name='SumoProtocol',
  full_name='sumoprotocol.SumoProtocol',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=348,
  serialized_end=429,
  methods=[
  _descriptor.MethodDescriptor(
    name='SumoIO',
    full_name='sumoprotocol.SumoProtocol.SumoIO',
    index=0,
    containing_service=None,
    input_type=_MOTORCOMMAND,
    output_type=_SENSORS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUMOPROTOCOL)

DESCRIPTOR.services_by_name['SumoProtocol'] = _SUMOPROTOCOL

# @@protoc_insertion_point(module_scope)
